### ISSUE TITLE
On django 1.9, the instructions when ssh-ing into the vagrant box are incorrect

### ISSUE THREAD

**Issue by zersiax** [FlipperPA/django-python3-vagrant#3]
I just tried to follow the instructions that are listed when ssh-ing into the vagrant box or when running 'menu'. During the pip install command, django 1.9 was retrieved. Running django-admin startproject works as expected, however when running manage.py runserver you get an import error:
"No module named django"

To fix, I had to substitute pip install with pip3 install within the virtualenv.

**Comment by FlipperPA** [comment]
Thank you, 1.9 was just released. I'll get this fixed up tomorrow.
